name: CI

on: [push, pull-request]

  jobs:
    build-and-test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'temurin'
            cashe: 'maven'
        - name: Build & test
        - name: Make mvnw executable
          run: chmod +x mvnw
          run: mvn -B clean verify
        - uses: actions/upload-artifact@v4
          with: 
            name: jacoco-report
            path: target/site/jacoco/
